"""
risk_routes.py – FastAPI APIRouter for ingredient risk analysis.

Endpoint:
  GET  /api/risk/scan/{upc}       – full scan: product lookup + risk analysis
                                    (the main endpoint the mobile app calls
                                     immediately after scanning a barcode)

The /api/risk/scan/{upc} endpoint is the recommended entry point for the
barcode-scan flow: it combines product lookup, recall check, allergen
detection, and diet compatibility into a single response so the frontend
can render the full risk card in one round-trip.
"""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from database import execute_query
from ingredient_risk_engine import analyse_product_risk
from barcode_routes import _lookup_off, _cache_product, format_recall, check_recall

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/risk", tags=["risk"])


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_user_profile(user_id: int) -> dict:
    """
    Fetch allergens and diet_preferences for a user from the DB.
    Returns {"allergens": [...], "diets": [...]}.
    """
    rows = execute_query(
        "SELECT allergens, diet_preferences FROM users WHERE id = %s LIMIT 1;",
        (user_id,),
    )
    if not rows:
        return {"allergens": [], "diets": []}
    row = rows[0]
    allergens = row.get("allergens") or []
    diets     = row.get("diet_preferences") or []
    # Handle case where DB stores as comma-separated string instead of array
    if isinstance(allergens, str):
        allergens = [a.strip() for a in allergens.split(",") if a.strip()]
    if isinstance(diets, str):
        diets = [d.strip() for d in diets.split(",") if d.strip()]
    return {"allergens": allergens, "diets": diets}


def _resolve_product(upc: str) -> Optional[dict]:
    """Look up product in DB cache, then Open Food Facts. Returns product dict or None."""
    rows = execute_query("SELECT * FROM products WHERE upc = %s LIMIT 1;", (upc,))
    if rows:
        return rows[0]
    off_data = _lookup_off(upc)
    if off_data:
        _cache_product(off_data)
        return off_data
    return None


def _load_recall_summary(recall_id: Optional[int]) -> Optional[dict]:
    """
    Load the LLM-generated plain-language summary for a recall.

    Stored in: recalls.plain_language_summary (JSONB column)
    Generated by: llm_service.explain_recall() called during recall refresh
    Returns: { headline, what_happened, what_to_do, who_is_at_risk, severity_plain }
             or None if not yet generated.
    """
    if not recall_id:
        return None
    try:
        rows = execute_query(
            "SELECT plain_language_summary FROM recalls WHERE id = %s LIMIT 1;",
            (recall_id,),
        )
        if rows and rows[0].get("plain_language_summary"):
            summary = rows[0]["plain_language_summary"]
            return summary if isinstance(summary, dict) else None
    except Exception:
        pass  # Column may not exist yet — graceful fallback
    return None


# ── Endpoint ──────────────────────────────────────────────────────────────────

@router.get("/scan/{upc}")
async def scan_barcode_with_risk(
    upc: str,
    user_id: Optional[int] = Query(None, description="Logged-in user ID for personalised risk"),
    enable_ai: bool = Query(False, description="Enable LLM disambiguation for ambiguous ingredients"),
):
    """
    **Primary barcode-scan endpoint.**

    Combines product lookup → recall check → allergen detection → diet check
    into a single response.  The frontend calls this immediately after the
    camera decodes a barcode.

    Query params:
      ?user_id=42      – personalise risk against this user's profile
      ?enable_ai=true  – enable LLM ingredient disambiguation (see llm_service.py)

    When enable_ai=true:
      The engine runs its normal 3-pass deterministic detection first,
      then sends ambiguous tokens ("natural flavors", "spices", etc.) to
      AWS Bedrock Claude Haiku for classification.  Results are cached
      per-token in the disambiguation_cache table so the LLM is called
      at most once per unique ambiguous ingredient, ever.

    When enable_ai=false (default):
      Deterministic-only analysis.  No Bedrock call.  <50ms.

    Response shape:
    {
      "found": true,
      "product": { upc, product_name, brand_name, category, ingredients, image_url },
      "recall":  { ..., "summary": { headline, what_happened, what_to_do, ... } } | null,
      "verdict": "DONT_BUY",
      "explanation": [
        "Active FDA recall reported on 2025-01-15",
        "Contains milk (your allergen) — detected 'whole milk'"
      ],
      "risk": { verdict, explanation, hard_stops, caution_signals, ... }
    }
    """
    product = _resolve_product(upc)
    if not product:
        return {
            "found":       False,
            "upc":         upc,
            "message":     "Product not found. Please enter details manually.",
            "verdict":     None,
            "explanation": [],
            "risk":        None,
        }

    # Load user profile if signed in
    allergens: list[str] = []
    diets: list[str] = []
    if user_id:
        profile = _load_user_profile(user_id)
        allergens = profile["allergens"]
        diets     = profile["diets"]

    recall_info = check_recall(
        upc,
        product_name=product.get("product_name") or "",
        brand_name=product.get("brand_name") or "",
    )
    ingredients_text = product.get("ingredients") or ""

    # ── Load plain-language recall summary if available ────────────────
    #    Generated by llm_service.explain_recall() during recall refresh.
    #    Stored in recalls.plain_language_summary JSONB column.
    if recall_info:
        recall_info["summary"] = _load_recall_summary(recall_info.get("id"))

    # Parse ingredients for display
    ingredients_raw = ingredients_text
    ingredients_list = [
        i.strip()
        for i in ingredients_raw.replace("|", ",").split(",")
        if i.strip()
    ]

    report = analyse_product_risk(
        ingredients_text=ingredients_text,
        user_allergens=allergens,
        user_diets=diets,
        is_recalled=recall_info is not None,
        recall_date=recall_info.get("recall_date") if recall_info else None,
        enable_llm=enable_ai,
    )

    # ── Build typed notifications for the frontend ────────────────────
    #    All deterministic — no LLM involved.
    #    Each notification has: type, severity, title, message
    #    Frontend can render these as colored cards/banners directly.
    notifications = _build_notifications(report)

    return {
        "found":       True,
        "product": {
            "upc":          product.get("upc"),
            "product_name": product.get("product_name"),
            "brand_name":   product.get("brand_name") or "",
            "category":     product.get("category") or "Unknown",
            "ingredients":  ingredients_list,
            "image_url":    product.get("image_url") or "",
        },
        "recall":      recall_info,
        # ── Decision-first UX ─────────────────────────────────────────
        "verdict":     report.verdict,
        "explanation": report.explanation,
        "notifications": notifications,
        # ── Full structured detail (drill-down / analytics) ───────────
        "risk":        report.to_dict(),
    }


# ── Notification builder (deterministic — no LLM) ─────────────────────────────

# Gate/category → notification type and severity mapping
_GATE_TO_NOTIFICATION = {
    "RECALL":      ("RECALL",   "HIGH"),
    "ALLERGEN":    ("ALLERGEN", "HIGH"),
    "DIET_STRICT": ("DIET",    "HIGH"),
}

_CATEGORY_TO_NOTIFICATION = {
    "CROSS_CONTACT":   ("ALLERGEN", "MEDIUM"),
    "ADDITIVE":        ("ADDITIVE", "LOW"),
    "DIET_SOFT":       ("DIET",     "MEDIUM"),
    "LOW_CONFIDENCE":  ("WARNING",  "MEDIUM"),
    "AMBIGUOUS":       ("WARNING",  "LOW"),
}


def _build_notifications(report) -> list[dict]:
    """
    Convert hard stops and caution signals into a flat, typed notification
    array the frontend can render directly as colored cards or banners.

    Each notification:
      {
        "type":     "RECALL" | "ALLERGEN" | "DIET" | "ADDITIVE" | "WARNING",
        "severity": "HIGH" | "MEDIUM" | "LOW",
        "title":    short headline for the card,
        "message":  full explanation text
      }

    Ordered by severity: HIGH first, then MEDIUM, then LOW.
    All deterministic — no LLM involved.
    """
    notifications: list[dict] = []

    # Hard stops → HIGH severity notifications
    for h in report.hard_stops:
        ntype, severity = _GATE_TO_NOTIFICATION.get(h.gate, ("WARNING", "HIGH"))

        if h.gate == "RECALL":
            title = "Active Recall"
        elif h.gate == "ALLERGEN":
            # Extract allergen name from the reason text
            title = "Allergen Detected"
            for m in report.allergen_matches:
                if m.matched_token in h.reason or m.allergen.lower() in h.reason.lower():
                    title = f"Allergen: {m.allergen}"
                    break
        elif h.gate == "DIET_STRICT":
            title = "Diet Violation"
            for f in report.diet_flags:
                if f.flagged_token in h.reason:
                    title = f"Not {f.diet}"
                    break
        else:
            title = "Warning"

        notifications.append({
            "type":     ntype,
            "severity": severity,
            "title":    title,
            "message":  h.reason,
        })

    # Caution signals → MEDIUM/LOW severity notifications
    for s in report.caution_signals:
        ntype, severity = _CATEGORY_TO_NOTIFICATION.get(s.category, ("WARNING", "LOW"))

        if s.category == "CROSS_CONTACT":
            title = "Cross-Contact Advisory"
        elif s.category == "ADDITIVE":
            title = "Additive Flag"
        elif s.category == "DIET_SOFT":
            title = "Diet Preference"
        elif s.category == "LOW_CONFIDENCE":
            title = "Low Confidence"
        else:
            title = "Note"

        notifications.append({
            "type":     ntype,
            "severity": severity,
            "title":    title,
            "message":  s.detail,
        })

    return notifications