"""
risk_routes.py – FastAPI APIRouter for ingredient risk analysis.

Endpoint:
  GET  /api/risk/scan/{upc}       – full scan: product lookup + risk analysis
                                    (the main endpoint the mobile app calls
                                     immediately after scanning a barcode)

The /api/risk/scan/{upc} endpoint is the recommended entry point for the
barcode-scan flow: it combines product lookup, recall check, allergen
detection, and diet compatibility into a single response so the frontend
can render the full risk card in one round-trip.
"""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from database import execute_query
from ingredient_risk_engine import analyse_product_risk
from barcode_routes import _lookup_off, _cache_product, format_recall

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/risk", tags=["risk"])


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_user_profile(user_id: int) -> dict:
    """
    Fetch allergens and diet_preferences for a user from the DB.
    Returns {"allergens": [...], "diets": [...]}.
    """
    rows = execute_query(
        "SELECT allergens, diet_preferences FROM users WHERE id = %s LIMIT 1;",
        (user_id,),
    )
    if not rows:
        return {"allergens": [], "diets": []}
    row = rows[0]
    allergens = row.get("allergens") or []
    diets     = row.get("diet_preferences") or []
    # Handle case where DB stores as comma-separated string instead of array
    if isinstance(allergens, str):
        allergens = [a.strip() for a in allergens.split(",") if a.strip()]
    if isinstance(diets, str):
        diets = [d.strip() for d in diets.split(",") if d.strip()]
    return {"allergens": allergens, "diets": diets}


def _resolve_product(upc: str) -> Optional[dict]:
    """Look up product in DB cache, then Open Food Facts. Returns product dict or None."""
    rows = execute_query("SELECT * FROM products WHERE upc = %s LIMIT 1;", (upc,))
    if rows:
        return rows[0]
    off_data = _lookup_off(upc)
    if off_data:
        _cache_product(off_data)
        return off_data
    return None


def _check_recall(upc: str) -> Optional[dict]:
    """Return the latest recall for this UPC, or None."""
    rows = execute_query(
        "SELECT * FROM recalls WHERE upc = %s ORDER BY recall_date DESC LIMIT 1;",
        (upc,),
    )
    return format_recall(rows[0]) if rows else None


def _load_recall_summary(recall_id: Optional[int]) -> Optional[dict]:
    """
    Load the LLM-generated plain-language summary for a recall.

    Stored in: recalls.plain_language_summary (JSONB column)
    Generated by: llm_service.explain_recall() called during recall refresh
    Returns: { headline, what_happened, what_to_do, who_is_at_risk, severity_plain }
             or None if not yet generated.
    """
    if not recall_id:
        return None
    try:
        rows = execute_query(
            "SELECT plain_language_summary FROM recalls WHERE id = %s LIMIT 1;",
            (recall_id,),
        )
        if rows and rows[0].get("plain_language_summary"):
            summary = rows[0]["plain_language_summary"]
            return summary if isinstance(summary, dict) else None
    except Exception:
        pass  # Column may not exist yet — graceful fallback
    return None


# ── Endpoint ──────────────────────────────────────────────────────────────────

@router.get("/scan/{upc}")
async def scan_barcode_with_risk(
    upc: str,
    user_id: Optional[int] = Query(None, description="Logged-in user ID for personalised risk"),
    enable_ai: bool = Query(False, description="Enable LLM disambiguation for ambiguous ingredients"),
):
    """
    **Primary barcode-scan endpoint.**

    Combines product lookup → recall check → allergen detection → diet check
    into a single response.  The frontend calls this immediately after the
    camera decodes a barcode.

    Query params:
      ?user_id=42      – personalise risk against this user's profile
      ?enable_ai=true  – enable LLM ingredient disambiguation (see llm_service.py)

    When enable_ai=true:
      The engine runs its normal 3-pass deterministic detection first,
      then sends ambiguous tokens ("natural flavors", "spices", etc.) to
      AWS Bedrock Claude Haiku for classification.  Results are cached
      per-token in the disambiguation_cache table so the LLM is called
      at most once per unique ambiguous ingredient, ever.

    When enable_ai=false (default):
      Deterministic-only analysis.  No Bedrock call.  <50ms.

    Response shape:
    {
      "found": true,
      "product": { upc, product_name, brand_name, category, ingredients, image_url },
      "recall":  { ..., "summary": { headline, what_happened, what_to_do, ... } } | null,
      "verdict": "DONT_BUY",
      "explanation": [
        "Active FDA recall reported on 2025-01-15",
        "Contains milk (your allergen) — detected 'whole milk'"
      ],
      "risk": { verdict, explanation, hard_stops, caution_signals, ... }
    }
    """
    product = _resolve_product(upc)
    if not product:
        return {
            "found":       False,
            "upc":         upc,
            "message":     "Product not found. Please enter details manually.",
            "verdict":     None,
            "explanation": [],
            "risk":        None,
        }

    # Load user profile if signed in
    allergens: list[str] = []
    diets: list[str] = []
    if user_id:
        profile = _load_user_profile(user_id)
        allergens = profile["allergens"]
        diets     = profile["diets"]

    recall_info = _check_recall(upc)
    ingredients_text = product.get("ingredients") or ""

    # ── Load plain-language recall summary if available ────────────────
    #    Generated by llm_service.explain_recall() during recall refresh.
    #    Stored in recalls.plain_language_summary JSONB column.
    if recall_info:
        recall_info["summary"] = _load_recall_summary(recall_info.get("id"))

    # Parse ingredients for display
    ingredients_raw = ingredients_text
    ingredients_list = [
        i.strip()
        for i in ingredients_raw.replace("|", ",").split(",")
        if i.strip()
    ]

    report = analyse_product_risk(
        ingredients_text=ingredients_text,
        user_allergens=allergens,
        user_diets=diets,
        is_recalled=recall_info is not None,
        recall_date=recall_info.get("recall_date") if recall_info else None,
        enable_llm=enable_ai,
    )

    return {
        "found":       True,
        "product": {
            "upc":          product.get("upc"),
            "product_name": product.get("product_name"),
            "brand_name":   product.get("brand_name") or "",
            "category":     product.get("category") or "Unknown",
            "ingredients":  ingredients_list,
            "image_url":    product.get("image_url") or "",
        },
        "recall":      recall_info,
        # ── Decision-first UX ─────────────────────────────────────────
        "verdict":     report.verdict,
        "explanation": report.explanation,
        # ── Full structured detail (drill-down / analytics) ───────────
        "risk":        report.to_dict(),
    }